[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "qcutils"
version = "0.3.0"
authors = [
  { name="Spandan Anupam", email="s.anupam@fz-juelich.de" },
]
description = "Sweep and measurement utilities for qcodes"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
]
keywords = ["qcodes"]
dependencies = [
  "zarr",
  "qcodes",
  "scipy",
  "python-gitlab",
  "gitpython",
  "checksumdir"
]

[project.urls]
"Homepage" = "https://gitlab.com/squad-lab/qcutils"
"Bug Tracker" = "https://gitlab.com/squad-lab/qcutils/-/issues"
